import { FormItemType, GetUserType, RadioOption } from '../../types/types';

export const getUserProfileInformation = (data: GetUserType, options:RadioOption[]):FormItemType[] => [
  {
    name: 'firstName',
    label: 'Имя',
    isRequared: true,
    validationMassage: 'enter something',
    itemType: 'input',
    placeholder: 'Введите имя',
    value: data.firstName ?? '',
  },
  {
    name: 'surName',
    label: 'Фамилия',
    isRequared: true,
    validationMassage: 'enter something',
    itemType: 'input',
    placeholder: 'Введите фамилию',
    value: data.surName ?? '',
  },
  {
    name: 'lastName',
    label: 'Отчество',
    isRequared: true,
    validationMassage: 'enter something',
    itemType: 'input',
    placeholder: 'Введите отчество',
    value: data.lastName ?? '',
  },
  {
    name: 'birthday',
    label: 'Дата рождения',
    isRequared: true,
    validationMassage: 'enter something',
    itemType: 'datePicker',
    defaultValue: data.birthday ?? '',
  },
  {
    name: 'citizenship',
    label: 'Гражданство',
    isRequared: true,
    validationMassage: 'Введите ваше гражданство',
    itemType: 'input',
    placeholder: 'Введите страну проживания',
    value: data.citizenship ?? '',
  },
  {
    name: 'country',
    label: 'Страна проживания',
    isRequared: true,
    validationMassage: 'enter something',
    itemType: 'input',
    placeholder: 'Введите страну проживания',
    value: data.country ?? '',
  },
  {
    name: 'city',
    label: 'Город проживания',
    isRequared: true,
    validationMassage: 'enter something',
    itemType: 'input',
    placeholder: 'Введите город проживания',
    value: data.city ?? '',
  },
  {
    name: 'position',
    label: 'Позиция',
    isRequared: true,
    validationMassage: 'enter something',
    itemType: 'select',
    value: data.position,
    options,
    defaultValue: data.position,
  },
  {
    name: 'workLevelSkills',
    label: 'Опыт',
    isRequared: true,
    validationMassage: 'enter something',
    itemType: 'input',
    placeholder: 'Введите опыт',
    value: data.workSkillsString ?? '',
  },
  {
    name: 'professionalLevelName',
    label: 'Уровень',
    isRequared: true,
    validationMassage: 'pick something',
    itemType: 'select',
    value: data.workLevel === null ? '' : data.workLevel,
    defaultValue: data.workLevel ?? '',
    options,
  },
];
